# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' ]
    name: Java ${{ matrix.Java }} 
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
        env:
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
          SONAR_HOST: ${{ secrets.SONAR_HOST }}
      - run: echo "TEST $SONAR_HOST TEST"; mvn -B package --file pom.xml org.jacoco:jacoco-maven-plugin:prepare-agent install -DskipITs -Dgpg.skip=true -Dmaven.test.failure.ignore=false -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST
